name: DCO
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check DCO
        uses: tim-actions/dco@v2
