name: Spec Sanity
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'examples/**'
      - 'proof-gallery/**'
      - 'schema/**'

jobs:
  ajv-valid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g ajv-cli@5 ajv-formats
      - name: Validate expected-valid receipts
        run: |
          ajv validate -c ajv-formats -s docs/receipt.schema.json \
            -d "examples/*.json" \
            -d "proof-gallery/ok-*.json" \
            -d "proof-gallery/tampered-*.json" \
            -d "proof-gallery/borderline-*.json" \
            -d "proof-gallery/highrisk-*.json" \
            -d "proof-gallery/reanchor-*.json" \
            -d "proof-gallery/blocked-*.json"

  ajv-invalid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g ajv-cli@5 ajv-formats
      - name: Validate expected-invalid receipts (must fail)
        run: |
          set -e
          # Comanda trebuie să EȘUEZE pentru fișierele marcate invalid
          if ajv validate -c ajv-formats -s docs/receipt.schema.json -d "proof-gallery/*invalid*.json"; then
            echo "Expected invalid receipts to fail schema validation"; exit 1
          fi

  no-cdn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure no external CDN domains are referenced
        run: |
          # Căutăm DOAR domenii CDN în URL-uri, nu cuvântul „CDN” din text.
          ! grep -RniE "https?://[^\"']*(jsdelivr|unpkg|cdnjs|ajax\.googleapis\.com|fonts\.googleapis\.com|cdn\.[^/\"']+)" docs || { echo 'CDN refs found'; exit 1; }
