name: Validate examples
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm init -y
      - run: npm i ajv ajv-formats
      - run: |
          node - <<'JS'
          const fs = require('fs');
          const Ajv = require('ajv');
          const addFormats = require('ajv-formats');
          const ajv = new Ajv({allErrors:true, strict:false});
          addFormats(ajv);
          const schema = JSON.parse(fs.readFileSync('schema/receipt.schema.json','utf8'));
          const validate = ajv.compile(schema);
          const files = fs.readdirSync('examples').filter(f=>f.endsWith('.json'));
          let ok = true;
          for (const f of files) {
            const data = JSON.parse(fs.readFileSync(`examples/${f}`,'utf8'));
            const valid = validate(data);
            if (!valid) { console.error('FAIL', f, validate.errors); ok = false; }
            else { console.log('OK', f); }
          }
          if (!ok) process.exit(1);
          JS
